# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: inventory-app
type: Opaque
data:
  db-password: postgres
  jwt-secret-key: replace-with-output-of-openssl-rand-hex-32
  db-user: postgres
