# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: inventory-app
type: Opaque
data:
  db-password: <base64>        # echo -n "MonMotDePasse" | base64
  jwt-secret-key: <base64>
  db-user: <base64>
